[users.admin]
password_hash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9"
role = "admin"

[users.umkm]
password_hash = "58f52a2f2e8b1a9c1c8a44c2e3c90b61c2c7b9c1f6a8b4e9e6d6a2d8c7b8a6f5"
role = "umkm"
